title: Thomas Coquereau
email: coquereau.thomas@gmail.com
description: >- 
  Data Scientist @Smartway.
github_username: Cokral
minimal_mistakes_skin: contrast
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-include-cache

author:
  name   : "Thomas Coquereau"
  avatar : "/assets/images/naruto.png"
  bio    : "Data Scientist @Smartway"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Cokral"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Cokral"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
